sudo: required
language: minimal
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install: 
script:
- sh build.sh
before_deploy:
- "./ci/hashgen.sh"
deploy:
  provider: releases
  api_key:
    secure: kzsS54gxoVGfnFfJS8v8Q33lpBgUeNW5KfiVMCVBuFkyoUT6L86jq3HM/1Zg9iNyusQ8esP7OsADgbF6b8dCBU8HuK1g/w5P/lXYbgI7Zet2DMrMB8/3w34TcuUkMz9sB8x8c6Ynfe6wUmPPzVwoVNH7eaxAJvkl93PLP5j+HrkwMjzDHEe0g0QNbTXfcKVdxBDb2TlaDSeB9hWTzN9gwYEtzzWYQY8MfAJxpseGPFcWbpYnmB4j0g/NvIOq+6I7iTaKJMDI9DuhfT9aL/iH0CioHJkqOWotSpRtjIsDiafsHCloFKd1Ck9C3xzG6N7iv3n9E7yoXL7RWi7MyqN9E+PabRMni8bXUSOL1exNB+/4/q0YOWlQZB9btmckWPDP2LBriL1aS2YIo+OmuPRUS18ovFlZpLBKiWMMdLT3DBMNOQMe1FuqlAQGuJjNnPdA8oU/stzttjFdRrhitQ+ErEC9FmXvV7Nby2mKjecIGHNveKdzLLto6cgkuqPyzVrnmh5WLn9cmzPMTp5RsQ7IMYE8Kj+tQLSco8HnsezgaV+ydE4LL8rqmWVroihZNQ43N0W9s6lJhRGdO+tTZOYhJZfTVdxSIkpUBQ9JBJtvXZM3c08/nMA5GwTHMStA7iE2h2K8vc+VynyTWIHdXOnpAFOeFoqNPO+QBrKTDUgLVvE=
  file:
  - "./of-watchdog"
  - "./of-watchdog-armhf"
  - "./of-watchdog-arm64"
  - "./of-watchdog-darwin"
  - "./of-watchdog.exe"
  - "./of-watchdog.sha256"
  - "./of-watchdog-armhf.sha256"
  - "./of-watchdog-arm64.sha256"
  - "./of-watchdog-darwin.sha256"
  - "./of-watchdog.exe.sha256"
  skip_cleanup: true
  on:
    tags: true
